//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSC2019_Session5Entities : DbContext
    {
        public WSC2019_Session5Entities()
            : base("name=WSC2019_Session5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RockType> RockTypes { get; set; }
        public virtual DbSet<WellLayer> WellLayers { get; set; }
        public virtual DbSet<Well> Wells { get; set; }
        public virtual DbSet<WellType> WellTypes { get; set; }
    }
}
