//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetOdometer
    {
        public long ID { get; set; }
        public long AssetID { get; set; }
        public System.DateTime ReadDate { get; set; }
        public long OdometerAmount { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
